version: '2.1'

services:

  caddy:
    image: klutchell/caddy:armhf
    ports:
      - '80:80'
      - '443:443'
      - '2015:2015'
    volumes:
      - 'caddy_root:/www'
      - 'caddy_certs:/root/.caddy'

  ssh:
    image: klutchell/ssh:armhf
    ports:
      - '22:22'
    volumes:
      - 'ssh_data:/root/.ssh'

  duplicati:
    image: lsioarmhf/duplicati
    ports:
      - '8200:8200'
    volumes:
      - 'caddy_root:/source/caddy_root:ro'
      - 'ssh_data:/source/ssh_data:ro'

volumes:

  caddy_root:
  caddy_certs:
  ssh_data: