version: '2.1'

services:

  caddy:
    image: klutchell/caddy:armhf
    ports:
      - '80:80'
      - '443:443'
      - '2015:2015'
    volumes:
      - 'caddy_root:/www'
      - 'caddy_certs:/root/.caddy'

  ssh:
    image: klutchell/ssh:armhf
    ports:
      - '22:22'
    volumes:
      - 'ssh_data:/root/.ssh'

  volumerize:
    image: klutchell/volumerize:armhf
    environment:
      - 'VOLUMERIZE_SOURCE=/volumes'
    volumes:
      - 'volumerize_cache:/volumerize-cache'
      - 'caddy_root:/volumes/caddy_root:ro'
      - 'caddy_certs:/volumes/caddy_certs:ro'
      - 'ssh_data:/volumes/ssh_data:ro'

volumes:

  caddy_root:
  caddy_certs:
  ssh_data:
  volumerize_cache: