version: '2.1'

services:

  caddy:
    image: klutchell/caddy:armhf
    volumes:
      - 'caddy_data:/var/lib/caddy'
      - 'caddy_certs:/root/.caddy'
    ports:
      - '80:80'
      - '443:443'

  volumerize:
    image: klutchell/volumerize:armhf
    volumes:
      - 'volumerize_cache:/volumerize-cache'
      - 'caddy_data:/volumes/caddy_data:ro'
      - 'caddy_certs:/volumes/caddy_certs:ro'
    environment:
      - 'VOLUMERIZE_SOURCE=/volumes'

volumes:

  caddy_data:
  caddy_certs:
  volumerize_cache: